# Generated by Django 5.1.4 on 2024-12-12 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuddyChatAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={},
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='user_group',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='last_message',
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='is_admin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='UserGroupMemberCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('last_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message', to='BuddyChatAPI.groupmessage')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='user_group_copy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='BuddyChatAPI.usergroupmembercopy'),
        ),
    ]
