# Generated by Django 5.1.3 on 2024-12-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuddyChatAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.svg', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group_image',
            field=models.ImageField(default='group_images/default.svg', upload_to='group_images'),
        ),
    ]
