# Generated by Django 5.1.4 on 2024-12-12 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuddyChatAPI', '0002_alter_usergroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroupmembercopy',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='BuddyChatAPI.groupmember'),
        ),
    ]
