# Generated by Django 5.1.4 on 2024-12-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuddyChatAPI', '0003_alter_usergroupmembercopy_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('-message__date',)},
        ),
    ]
