# Generated by Django 5.1.3 on 2024-12-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuddyChatAPI', '0003_alter_chat_user1_alter_chat_user2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
