# Generated by Django 5.1.3 on 2024-12-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuddyChatAPI', '0004_alter_usergroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
