# Generated by Django 5.1.3 on 2024-12-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuddyChatAPI', '0005_groupmember_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('user1', 'user2')},
        ),
    ]
