# Generated by Django 5.1.3 on 2024-12-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuddyChatAPI', '0008_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together={('number', 'country_code')},
        ),
    ]
