# Generated by Django 5.1.3 on 2024-12-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuddyChatAPI', '0009_alter_phonenumber_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-date',)},
        ),
    ]
